### ISSUE TITLE
Organizar los metodos de profesores y alumnos

### ISSUE THREAD

**Issue by saamnd** [saamnd/SportsHeaven#2]
Hola a todos, acabo de editar el header para que reciba el ROL por usuario (profesor o alumno)
Sería bueno organizar las opciones que tengan disponibles segun el rol la sesión iniciada (Modificar, Crear)

**Comment by ValeriaWatanabe** [comment]
Para solucionar esto, lo que realizé fue partir la tabla usuarios por otras dos tablas que fueran alumnos y profesores. De este modo, solo aquellos objetos que se encuentren en la tabla profesores puedan realizar los métodos correspondientes a profesores. Lo mismo sería con alumnos.
